name: Publish MoBrix-backend package

on: workflow_dispatch

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{steps.setup-env.outputs.LATEST_VERSION }}
      pkg-json-version: ${{steps.setup-env.outputs.PACKAGE_JSON_VERSION }}
      changelog-index-version: ${{steps.setup-env.outputs.CHANGELOG_INDEX_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        id: setup-env
        run: |
          echo "LATEST_VERSION=$(curl -s https://registry.npmjs.org/mobrix-backend/latest -H "Accept: application/json" | jq -r '.version')" >> "$GITHUB_OUTPUT"
          echo "PACKAGE_JSON_VERSION=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
          echo "CHANGELOG_INDEX_VERSION=$(cat package.json | jq -r '.version' | tr -d .)" >> "$GITHUB_OUTPUT"
  publish-mobrix-backend-package:
    runs-on: ubuntu-latest
    needs: [setup-env]
    env:
      PACKAGE_JSON_VERSION: ${{ needs.setup-env.outputs.pkg-json-version }}
      LATEST_VERSION: ${{ needs.setup-env.outputs.latest-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org/"
          always-auth: "true"
      - name: Create release
        run: |
          npm ci

          output=$(node ./scripts/check-version.js)

          if [ $output -eq 1 ]; then
            echo "Creating release..."
            
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CianciarusoCataldo/mobrix-backend/releases \
            -d '{"tag_name":"v${{ needs.setup-env.outputs.pkg-json-version }}","target_commitish":"main","name":"mobrix-backend-v${{ needs.setup-env.outputs.pkg-json-version }}","body":"Release notes available at https://cianciarusocataldo.github.io/mobrix-backend/docs/Changelog/#${{ needs.setup-env.outputs.changelog-index-version }}","draft":false,"prerelease":false,"generate_release_notes":false}'
          else
            echo "Not a minor or major version bump, release won't be created"
          fi
      - name: Publish to npm registry
        run: |
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@cianciarusocataldo"
          always-auth: "true"
      - name: Publish to github registry
        run: |
          npx --yes json -I -f package.json -e "this.name=\"@cianciarusocataldo/mobrix-backend\""
          npx --yes json -I -f package.json -e "this.publishConfig={\"registry\": \"https://npm.pkg.github.com\"}"
          npm i
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
